### ISSUE TITLE
sample dataset

### ISSUE THREAD

**Issue by ghost** [pievos101/GNN-SubNet#1]
Hi

Would it be possible to provide some example or test datasets so we can make sure that the method is working correctly?

Thank you!

**Comment by pievos101** [comment]
Thanks!

We have added TCGA datasets to our repository (see datasets/TCGA).
Let us know whether this was helpful.
We will also add some synthetic datasets.

All the best, Bastian

**Comment by pievos101** [comment]
Datasets are now included.
